name: Compile and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    name: Compile and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update -qq
      #     sudo apt-get install -y yq
      
      - name: Bootstrap with autoconf
        run: ./autogen.sh
        
      - name: Configure
        run: ./configure

      - name: Compile
        run: make
        
      - name: Run tests
        run: make check || (cat ./test-suite.log && exit 1)

